version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "9000:5432"
    environment:
      - POSTGRES_DB=twitterClone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    image: wusa889/twitterclone-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/twitterClone
    command: >
      sh -c "
      sleep 10 &&
      npm install &&
      npm run migration:generate &&
      npm run migration:push &&
      npm run db:seed &&
      npx ts-node ./src/index.ts
      "
